// Generated by dzn code from /home/karol/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/src/scene_module/stop_line/scene_dezyne.dzn
#include "scene_dezyne.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace dzn
{
  char const*
  to_cstr (::State v)
    {
      switch (v)
        {
          case ::State::APPROACH: return "State:APPROACH";
          case ::State::STOPPED: return "State:STOPPED";
          case ::State::START: return "State:START";
        }
      return "";
    }
  template <>
  std::string
  to_string (::State v)
    {
      return to_cstr (v);
    }
}
namespace dzn
{
  ::State
  to_State (std::string s)
    {
      static std::map<std::string, ::State> m =   {
            {"State:APPROACH", ::State::APPROACH},
            {"State:STOPPED", ::State::STOPPED},
            {"State:START", ::State::START}};
      return m.at (s);
    }
}
IVehicleState::IVehicleState (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
, state (::State::APPROACH)
{}
IVehicleState::~IVehicleState ()= default;
void
IVehicleState::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IVehicleState::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 3599409592u:
      //0:updateState
      dzn_state = 1;
      break;
      case 1136467885u:
      //1:State:APPROACH
      dzn_state = 0;
      state = State::APPROACH;
      break;
      case 8237912u:
      //1:State:START
      dzn_state = 2;
      state = State::START;
      break;
      case 3712971843u:
      //1:State:STOPPED
      dzn_state = 3;
      state = State::STOPPED;
      break;
      case 3599409750u:
      //2:updateState
      dzn_state = 1;
      break;
      case 3599409829u:
      //3:updateState
      dzn_state = 1;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IVehicleState::dzn_check_bindings ()
{
  if (!this->in.updateState) throw dzn::binding_error (this->dzn_meta, "in.updateState");
}
namespace dzn
{
}
IApproach::IApproach (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
{}
IApproach::~IApproach ()= default;
void
IApproach::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IApproach::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 196803356u:
      //0:ApproachStuff
      dzn_state = 1;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IApproach::dzn_check_bindings ()
{
  if (!this->in.ApproachStuff) throw dzn::binding_error (this->dzn_meta, "in.ApproachStuff");
}
namespace dzn
{
}
IStopped::IStopped (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
{}
IStopped::~IStopped ()= default;
void
IStopped::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IStopped::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 614566456u:
      //0:StoppedStuff
      dzn_state = 1;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IStopped::dzn_check_bindings ()
{
  if (!this->in.StoppedStuff) throw dzn::binding_error (this->dzn_meta, "in.StoppedStuff");
}
namespace dzn
{
}
IStart::IStart (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
{}
IStart::~IStart ()= default;
void
IStart::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IStart::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 4188205965u:
      //0:StartStuff
      dzn_state = 1;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IStart::dzn_check_bindings ()
{
  if (!this->in.StartStuff) throw dzn::binding_error (this->dzn_meta, "in.StartStuff");
}
namespace dzn
{
}
ModifyPathVelocity::ModifyPathVelocity (dzn::locator const& locator)
: dzn_meta ({"ModifyPathVelocity","ModifyPathVelocity",0,  {},  {},  {[this] ()
        {
          vehicleState.dzn_check_bindings ();
        }, [this] ()
        {
          approach.dzn_check_bindings ();
        }, [this] ()
        {
          start.dzn_check_bindings ();
        }, [this] ()
        {
          stop.dzn_check_bindings ();
        }}})
, dzn_runtime (locator.get<dzn::runtime> ())
, dzn_locator (locator)
, vehicleState ({  {"vehicleState",&vehicleState,this,&dzn_meta},  {"vehicleState",0,0,0}},this)
, approach ({  {"approach",0,0,0},  {"approach",&approach,this,&dzn_meta}},this)
, start ({  {"start",0,0,0},  {"start",&start,this,&dzn_meta}},this)
, stop ({  {"stop",0,0,0},  {"stop",&stop,this,&dzn_meta}},this)
{
  this->dzn_meta.require =   {&approach.dzn_meta,&start.dzn_meta,&stop.dzn_meta};
  this->dzn_runtime.performs_flush (this) = true;
  this->vehicleState.in.updateState = [this] ()
    {
      this->dzn_out_vehicleState = &this->vehicleState.in.updateState.dzn_out_binding;
      this->dzn_reply_State = &this->vehicleState.in.updateState.reply;
      this->vehicleState_updateState ();
      return this->vehicleState.in.updateState.reply;
    };
}
void
ModifyPathVelocity::vehicleState_updateState ()
{
  if (vehicleState.state == ::State::APPROACH)
    {
      this->approach.in.ApproachStuff ();
      *this->dzn_reply_State = ::State::STOPPED;
      if ((*this->dzn_out_vehicleState)) (*this->dzn_out_vehicleState) ();
      (*this->dzn_out_vehicleState) = nullptr;
    }
  else if (vehicleState.state == ::State::STOPPED)
    {
      this->stop.in.StoppedStuff ();
      *this->dzn_reply_State = ::State::START;
      if ((*this->dzn_out_vehicleState)) (*this->dzn_out_vehicleState) ();
      (*this->dzn_out_vehicleState) = nullptr;
    }
  else if (vehicleState.state == ::State::START)
    {
      this->start.in.StartStuff ();
      *this->dzn_reply_State = ::State::APPROACH;
      if ((*this->dzn_out_vehicleState)) (*this->dzn_out_vehicleState) ();
      (*this->dzn_out_vehicleState) = nullptr;
    }
  else if (!(vehicleState.state == ::State::START) && (!(vehicleState.state == ::State::STOPPED) && !(vehicleState.state == ::State::APPROACH))) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
// version 2.18.0
